image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test

before_script:
    - cp "$SignersProps" ./oss.sdk.net/src/Samples/signers.properties
    - "dotnet restore ./src"

build:
    stage: build
    script:
        - "dotnet build ./src -c Release"

test:
    stage: test
    script: 
        - "dotnet test ./src -c Release"
